channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.3.1
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.0
name: mlflow-env
