# .github/workflows/main.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Upload mlruns to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_gdrive.py
